version: "3.8"

services:
  app:
    container_name: auto-image-rotator-app
    image: auto-image-rotator-app
    build:
      context: .
      dockerfile: Dockerfile
    command: python rotate.py ${OVERWRITE_FILES}
    volumes:
      - .:/app
      - ${IMAGES_PATH}:/images
